config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'words#index'

  get  '/translate',  to: 'words#new'
  post '/translate',  to: 'words#translate'
  get  '/events',     to: 'words#index'
  get  '/cards',     to: 'words#cards'
  get  '/search',     to: 'books#search'

  resources :books, :except => [:destroy]
  resources :events, :only => [] do
    resources :user_words, :only => [:index]
  end

end

app/views/shared/_footer.html.haml
%p.text-muted
  %br
  Powered by 半玩伴学，有建议发邮件:
  = mail_to "xbin999@gmail.com"

app/views/shared/_navigation.html.haml
%nav.navbar.navbar-default.navbar-fixed-top{:role => "navigation"}
  .container
    / Title
    .navbar-header.pull-left
      = link_to "首页", root_path, class: "navbar-brand"
      .nav-form.form-inline.pull-right
        = form_for :search, :url => search_path, :method => :get do |f|
          .input-group
            = f.text_field :name, as: :string, placeholder: "书名", label: false, input_html: {class:  'form-control'}
            = f.button :button, class: " navbar-btn input-group-button" do
              %span.glyphicon.glyphicon-search{"aria-hidden" => "true"}
    / 'Sticky' (non-collapsing) right-side menu item(s)
    .navbar-header.pull-right
      %ul.nav.pull-left
        / This works well for static text, like a username
        %li.pull-left
        / Add any additional bootstrap header items.  This is a drop-down from an icon
        - if user_signed_in?
          %li.dropdown.pull-right
            %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :role => "button"}
              = image_tag qiniu_image_path(check_avatar(current_user), :thumbnail => '32x32!')
              = current_user.name
              %span.caret
            %ul.dropdown-menu
              %li= link_to "修改资料", edit_user_registration_path
              %li.divider{:role => "separator"}
              %li= link_to "退出", destroy_user_session_path, method: :delete
        -else
          %li.dropdown-pull-right
            %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :role => "button"}
              账户
              %span.caret
            %ul.dropdown-menu
              %li= link_to "注册", new_user_registration_path
              %li= link_to "登录", new_user_session_path

      / Required bootstrap placeholder for the collapsed menu
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar

    / The Collapsing items            navbar-left or navbar-right
    .collapse.navbar-collapse.navbar-left
      / pull-right keeps the drop-down in line
      %ul.nav.navbar-nav.pull-right
        %li= link_to "阅读", books_path
        %li= link_to "词卡", cards_path
        %li= link_to "测试", "http://testyourvocab.com/", :target => "_blank"
  -#
    / Additional navbar items
    .collapse.navbar-collapse.navbar-right
      / pull-right keeps the drop-down in line
      %ul.nav.navbar-nav.pull-right
        %li
          = link_to new_book_path, class: "btn btn-default" do
            %i.glyphicon.glyphicon-plus 新书

app/views/shared/_sidebar.html.haml
.sidebar-module.sidebar-module-inset
  %h4 关于
  %p
    跟着阅读记单词，制作个性化的阅读书目的单词卡片，让单词不再孤单。
.sidebar-module
  %h4 标签
  = render :partial => 'books/tag', layout: 'layouts/layout'
.sidebar-module
  %h4 英语分级书查询
  %ol.list-unstyled
    %li
      %a{:href => "https://www.lexile.com/fab/", :target => "_blank"} Lexile
    %li
      %a{:href => "http://www.scholastic.com/parents/", :target => "_blank"} Scholastic
.sidebar-module
  %h4 参考文章
  %ol.list-unstyled
    %li
      %a{:href => "http://mp.weixin.qq.com/s?__biz=MjM5MDQzODAyMA==&mid=203613437&idx=1&sn=9d5d0a6a9b4a165294ab0ac0bd9f56dd", :target => "_blank"} 分级阅读的重要性
    %li
      %a{:href => "http://mp.weixin.qq.com/s?__biz=MjM5MDQzODAyMA==&mid=2651799514&idx=1&sn=20488609689cb96c18283e4522410745", :target => "_blank"} 小乐的单词学习
    %li
      %a{:href => "http://mp.weixin.qq.com/s?__biz=MjM5MDQzODAyMA==&mid=210338866&idx=1&sn=0bfd0e33f9d103d6410cccf14fd916e0", :target => "_blank"} 单词记忆曲线