config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'words#index'

  get  '/translate',  to: 'words#new'
  post '/translate',  to: 'words#translate'
  get  '/events',     to: 'words#index'
  get  '/cards',     to: 'words#cards'
  get  '/search',     to: 'books#search'

  resources :books, :except => [:destroy]
  resources :events, :only => [] do
    resources :user_words, :only => [:index]
  end

end

app/models/book.rb
class Book < ActiveRecord::Base
  validates_presence_of :name, :author, :cover

  has_attached_file :cover, :path => ":class/:attachment/:id/:basename.:extension"
#  has_attached_file :cover, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :path => ":class/:attachment/:id/:basename_:styles.:extension"
  validates :cover, :attachment_presence => true
  validates_attachment_content_type :cover, :content_type => /\Aimage\/.*\Z/

  has_many :events

  acts_as_taggable # Alias for acts_as_taggable_on :tags
  acts_as_taggable_on :genres

  before_post_process :rename_image_file

  def rename_image_file
    extension = File.extname(cover_file_name).downcase
    self.cover.instance_write(:file_name, "#{SecureRandom.hex(12)}#{extension}")
    #logger.debug("=== rename to #{self.cover_file_name}")
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, only: [:new]
  before_action :authenticate_admin, only: [:edit]
  before_action :find_book, only: [:show, :edit, :update, :destroy]
  def index
    #@books = Book.all.order("created_at DESC")
    if params[:tag] == nil
      @books = Book.all.paginate(page: params[:page], per_page: 20).order("created_at DESC")
    else
      @books = Book.tagged_with(params[:tag]).order("created_at DESC").paginate(:page => params[:page], :per_page => 20)
    end
  end

  def show
  end

  def new
    @book = Book.new
    @book.name = params[:book_name]
  end

  def create
    @book = Book.new(book_params)

    logger.debug("=== Saving book #{@book.name}")

    if @book.save
      @event = Event.new
      if user_signed_in?
        @event.name = current_user.name
        @event.user_id = current_user.id
      else
        @event.name = cookies[:card_name]
      end
      @event.book_name = @book.name
      @event.book_id = @book.id
      @event.event_type = Event.event_types["newbook"]
      if @event.save

      else
        logger.debug("=== Error in saving event...#{@event.errors.full_messages}")
      end
      redirect_to book_path(@book), notice: "Successfully created new book"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @book.update(book_params)
      redirect_to @book, notice: "book was successfully update!"
    else
      render 'edit'
    end
  end

  def destroy
    @book.destroy
    redirect_to root_path
  end

  def search
    # case insensitive
    @query = params[:search][:name].downcase
    logger.debug "===> search #{@query} ..."
    @books = Book.where("lower(name) LIKE ?", "%#{@query}%").paginate(page: params[:page], per_page: 15)
  end

  private

  def book_params
    params.require(:book).permit(:name,
      :author,
      :isbn,
      :press,
      :description,
      :grade_level,
      :lexile_level,
      :douban_link,
      :scholastic_link,
      :cover,
      :page_number,
      :tag_list)
  end

  def find_book
    @book = Book.find(params[:id])
  end

  def authenticate_admin
    authenticate_user!

    if current_user.admin?
      return
    else
      redirect_to root_path
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.haml
//%h1 新增书籍
//%br

.record-form

  = simple_form_for book, html: { multipart: true, class: 'form-horizontal'}, wrapper: :horizontal_form, wrapper_mappings: {file: :horizontal_file_input} do |f|

    = f.input :name, label: '书名', placeholder: "书名", input_html: {class:  'form-control'}
    = f.input :author, label: '作者', placeholder: "作者名称", input_html: {class:  'form-control'}
    = f.input :isbn, label: 'ISBN', input_html: {class:  'form-control'}
    = f.input :press, label: '出版社', input_html: {class:  'form-control'}
    = f.input :page_number, label: '页数', input_html: {class:  'form-control'}
    = f.input :cover, label: '封面', input_html: {class:  'form-control'}
    = f.input :tag_list, as: :text, label: '分类', hint: '以,间隔', input_html: {class:  'form-control'}
    = f.input :description, label: '内容简介', as: :text, input_html: {class:  'form-control', rows: 5}
    = f.input :douban_link, label: '豆瓣链接', placeholder: 'https://book.douban.com/subject/XXXXXXXX/', hint: '豆瓣上该书的链接地址，查看评分和书评。',input_html: {class:  'form-control'}
    = f.input :scholastic_link, label: 'Scholastic链接', placeholder: 'http://www.scholastic.com/parents/book/XXXXXXXX', hint: 'Scholastic网站该书的链接地址，查询Grade Level Equivalent（年级水平）和Lexile Measure（兰斯分值）。', input_html: {class:  'form-control'}
    = f.input :grade_level, label: '年级水平', placeholder: "类似以5.9表示", input_html: {class:  'form-control'}
    = f.input :lexile_level, label: '兰斯分值(L)', placeholder: "类似以700表示", input_html: {class:  'form-control'}

    = f.button :submit, "保存", class: "btn btn-success btn-lg btn-block", :disable_with => "Submitting…"

app/views/books/_tag.html.haml
/- ActsAsTaggableOn::Tag.most_used(10).each do |tag|
- Book.tag_counts_on(:tags).limit(20).order('count desc').each do |tag|
	= link_to tag.name, books_path(:tag => tag.name)

app/views/books/edit.html.haml
.row
  = render :partial => 'form', layout: 'layouts/layout', :locals => { :book => @book }

app/views/books/index.html.haml
//= javascript_include_tag "//www.google.com/jsapi", "chartkick"
//%h1 所有书籍
%br

.row
  - @books.each_slice(4) do |books|
    .row
      - books.each do |book|
        .book.col-md-3.col-sm-6.small
          = link_to image_tag(qiniu_image_path(book.cover.url, :thumbnail => '130x130>')), book_path(book)
          %br
          = link_to truncate(book.name, length:24), book_path(book)
    %br
  
%br   
#static-pagination
  = will_paginate @books

app/views/books/new.html.haml
.row
  = render :partial => 'form', layout: 'layouts/layout', :locals => { :book => @book }

app/views/books/search.html.haml
//= javascript_include_tag "//www.google.com/jsapi", "chartkick"
- if !@books.empty?
  .index
    - @books.each do |book|
      .row
        %hr
        .book.col-sm-1.small
          = link_to image_tag(qiniu_image_path(book.cover.url, :thumbnail => '100x100>')), book_path(book)
        
        .info.col-sm-6.col-sm-offset-1
          %p.name= link_to book.name, book_path(book)
          .small
            %p
              = "#{book.author} / #{book.press} / #{book.page_number}页 / #{book.grade_level} / #{book.lexile_level}L"
            %p 
              = link_to "豆瓣", book.douban_link if book.douban_link
              = link_to "Scholastic", book.scholastic_link if book.scholastic_link
       
    #static-pagination
      = will_paginate @books
- else 
  %h3 没有找到“#{@query}”
  %p
    %a.btn.btn-success{:href => new_book_path("book_name" => "#{@query}")} 新增一本

app/views/books/show.html.haml
%h3= @book.name
%br

.row
  .subjectwrap

    #cover.col-sm-2
      = image_tag qiniu_image_path(@book.cover.url, :thumbnail => '150x150>')

    .info.col-sm-5.col-sm-offset-1.small
      %p.author= "作者：#{@book.author}"
      %p.isbn= "ISBN：#{@book.isbn}"
      %p.press= "出版社：#{@book.press}"
      %p.page_numeber= "页数：#{@book.page_number}"
      %p.grade_level= "年级水平：#{@book.grade_level}"
      %p.lexile_level= "兰斯分值：#{@book.lexile_level}L"
      %p.douban
        = link_to "豆瓣", @book.douban_link if @book.douban_link
        = link_to "Scholastic", @book.scholastic_link if @book.scholastic_link

//= link_to "制作词卡", translate_path
%a.btn.btn-success{:href => translate_path("book_id" => "#{@book.id}", "book_name" => "#{@book.name}")} 制作词卡
- if !current_user.nil? && current_user.admin?
  %a.btn.btn-success{:href => edit_book_path(@book)} 修改书籍

.description
  内容简介：
  %p.description= simple_format(@book.description)