config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'words#index'

  get  '/translate',  to: 'words#new'
  post '/translate',  to: 'words#translate'
  get  '/events',     to: 'words#index'
  get  '/cards',     to: 'words#cards'
  get  '/search',     to: 'books#search'

  resources :books, :except => [:destroy]
  resources :events, :only => [] do
    resources :user_words, :only => [:index]
  end

end

app/models/word.rb
# encoding: utf-8

class Word < ActiveRecord::Base
  validates_presence_of :name, :explains
  has_many :user_words

  def to_cover(sentence = nil)
    target ||= []

    if self.translate_type == "英译中"
      target << "us: [#{self.us_phonetic}]  uk: [#{self.uk_phonetic}]"
    else
      if self.phonetic != nil
        target << "[#{self.phonetic}]"
      end
    end
    target << self.explains
    if sentence != nil || sentence != ""
      target << sentence
    end

    return target
  end
end

app/controllers/words_controller.rb
# encoding: utf-8

require 'nokogiri'
require 'open-uri'
require 'json'
require 'bing_translator'

class WordsController < ApplicationController
  #before_action :show_message, only: [:new]
  before_action :authenticate_user!, only: [:new, :translate]

  def index
    #byebug
    @events = Event.all.paginate(page: params[:page], per_page: 20).order(created_at: :desc)
  end

  def cards
    if user_signed_in?
      @mycards = Event.includes(:book).where("user_id=? and event_type=?", current_user.id, Event.event_types["newcard"]).paginate(page: params[:page], per_page: 20).order(created_at: :desc)
    end
    @recentcards = Event.includes(:book).where("event_type=?", Event.event_types["newcard"]).paginate(page: params[:page], per_page: 20).order(created_at: :desc)
  end

  def new
    @event = Event.new
    if user_signed_in?
      @event.name = current_user.name
      @event.user_id = current_user.id
    else
      @event.name = cookies[:card_name]
    end
    @event.age = cookies[:card_age]
    #@event.book_name = cookies[:card_book]
    @event.book_id = params[:book_id]
    @event.book_name = params[:book_name]
  end

  def translate
    @event = Event.new(event_params)
    @event.event_type = Event.event_types["newcard"]
    if @event.valid?
      cookies[:card_name] = {value: @event.name, expires: 1.year.from_now}
      cookies[:card_age]  = {value: @event.age, expires: 1.year.from_now}
      cookies[:card_book] = {value: @event.book_name, expires: 1.year.from_now}

      @source = @event.words
      logger.debug "translate #{@source}..."
      @target = Hash.new
      @error_words = Array.new
      n = 0
      sep = get_sep(@source)

      if sep == "#"
        # not #To be or not to be# follow #Harry potter, follow me#
        @source.scan(/([[:word:]]+)\ *#(.*?)#/).each do |word, sentence|
          if saveto_targets(word, sentence)
            n += 1
          end
        end
      else
        # hello,world,hurry up,good
        # or hello word
        @source.split(sep).each do |word|
          if saveto_targets(word)
            n += 1
          end
        end
      end
      @event.count = n

      @target.each do |word, value|
        @event.user_words.build(:word => word, :sentence => value, :book_id => @event.book_id, :user_id => @event.user_id)
      end
      if @event.save
        logger.info("=== Success in saving event: #{@event.id}")
        if @error_words.empty?
          redirect_to event_user_words_path(@event), notice: "成功创建词卡。"
        else
          redirect_to event_user_words_path(@event), notice: "成功创建词卡，剩余错误单词: #{@error_words.join(',')}"
        end
      else
        logger.error("=== Error in saving event...#{@event.errors.full_messages}")
        flash[:error] = @event.errors.full_messages.to_sentence
        render "words/new.html.haml"
      end

      #render :json => @target.to_json
      #render 'translate'
=begin
      respond_to do |format|
        format.html
        format.pdf do
          render pdf: "#{@event.name}_#{@event.book}_#{@event.id}",
                 :template => 'words/translate.html.haml',
                 :layout => "pdf.html.haml"
        end
      end
=end
    else
      flash[:error] = @event.errors.full_messages.to_sentence
      render "words/new.html.haml"
      #redirect_to translate_path
    end

  end

private
  def convert(source, sentence=nil)
    target ||= []
    # http://fanyi.youdao.com/openapi.do?keyfrom=XXXXXX&key=XXXXXXXX&type=data&doctype=json&version=1.1&q=hello
    logger.debug "http://fanyi.youdao.com/openapi.do?keyfrom=#{Rails.configuration.mysecrets['keyfrom']}&key=#{Rails.configuration.mysecrets['key']}&type=data&doctype=json&version=1.1&q=#{source}"
    doc = JSON.parse(open(URI.escape("http://fanyi.youdao.com/openapi.do?keyfrom=#{Rails.configuration.mysecrets['keyfrom']}&key=#{Rails.configuration.mysecrets['key']}&type=data&doctype=json&version=1.1&q=#{source}")).read)
    if doc.fetch('basic',{}).fetch('explains',nil) != nil
      if doc.fetch('basic',{}).fetch('us-phonetic',nil) != nil
        target << "us: [#{doc['basic']['us-phonetic']}]  uk: [#{doc['basic']['uk-phonetic']}]"
      else
        if doc.fetch('basic',{}).fetch('phonetic',nil) != nil
          target << "[#{doc['basic']['phonetic']}]"
        end
      end
      doc['basic']['explains'].each do |link|
        logger.debug "---> translate to #{link}"
        target << link
      end
      if sentence != nil
        target << sentence
      end
    end

    return target
  end

  def convert2object(source)
    source = source.strip
    word = Word.find_by name: source
    if word == nil
      begin
        # http://fanyi.youdao.com/openapi.do?keyfrom=XXXXXX&key=XXXXXXXX&type=data&doctype=json&version=1.1&q=hello
        logger.debug "http://fanyi.youdao.com/openapi.do?keyfrom=#{Rails.configuration.mysecrets['keyfrom']}&key=#{Rails.configuration.mysecrets['key']}&type=data&doctype=json&version=1.1&q=#{source}"
        doc = JSON.parse(open(URI.escape("http://fanyi.youdao.com/openapi.do?keyfrom=#{Rails.configuration.mysecrets['keyfrom']}&key=#{Rails.configuration.mysecrets['key']}&type=data&doctype=json&version=1.1&q=#{source}")).read)
      rescue URI::InvalidURIError
        logger.error "Error in translating #{word}, ingnore."
        return nil
      end

      word = Word.new
      word.name = source
      word.translate_tool = "youdao"

      if doc.fetch('basic',{}).fetch('explains',nil) != nil
        if doc.fetch('basic',{}).fetch('us-phonetic',nil) != nil
          word.us_phonetic = doc['basic']['us-phonetic']
          word.uk_phonetic = doc['basic']['uk-phonetic']
          word.translate_type = "英译中"
        else
          if doc.fetch('basic',{}).fetch('phonetic',nil) != nil
            word.phonetic = doc['basic']['phonetic']
            word.translate_type = "中译英"
          end
        end
        word.explains = ""
        doc['basic']['explains'].each do |link|
          word.explains << link << "\n"
        end
      end
      if word.save
        logger.info("=== Success in saving word: #{word.id}:#{word.name}")
      else
        logger.error("=== Error in saving word...#{word.errors.full_messages}")
        return nil
      end
    end

    return word
  end

  def saveto_targets(word, sentence=nil)
    rv = false

    if !word.strip.blank?
      w = convert2object(word)
      if w != nil
        @target[w] = sentence
        rv = true
      else
        @error_words << word
      end
    end
    return rv
  end

  def get_sep(source)
    if source.include? "#"
      sep = "#"
    else
      if @source.include? ","
        sep = ","
      else
        sep = " "
      end
    end
    return sep
  end

  def event_params
    params.require(:event).permit(:name, :words, :age, :book_name, :book_id, :user_id)
  end

  def show_message
    if !user_signed_in?
      flash[:notice] = "建议先登录，选择对应的书再制卡。"
    end
  end

  def save_words(wordsMap)
  end

end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/words/_display.html.haml
.index
  .row
    %blockquote
      %p 没有什么能够阻挡，我对自由的向往

  - events.each do |event|
    .row
      %hr
      /=event.to_view_str
      - case event.event_type
      - when "newcard"
        / TODO: display avatar
        /= image_tag qiniu_image_path(check_avatar(event.user_id), :thumbnail => '32x32!')
        ="@#{event.name} 制作了《"
        - if event.book_id
          %a{:href => book_path(event.book_id)}#{event.book_name}
        -else
          #{event.book_name}
        ="》书中的"
        %a{:href => event_user_words_path(event.id)}#{event.count || event.words.split(" ").count}张单词卡片
        ="。"
      - when "newbook"
        ="@#{event.name} 新增了《"
        - if event.book_id
          %a{:href => book_path(event.book_id)}#{event.book_name}
        -else
          #{event.book_name}
        ="》一书。"
      - else
        @#{event.name} @《#{event.book_name}》。

      %span.pull-right
        =" #{time_ago_in_words(event.created_at)}前  "

  #static-pagination
    = will_paginate events

%br

app/views/words/_displaycards.html.haml
.index

  - if !current_user.nil?
    %h3= "我的词卡..."
    %hr
    - mycards.each_slice(4) do |rows|
      .row
        - rows.each do |cards|
          .subjectwrap

            #cover.col-sm-1
              - if cards.book != nil
                = link_to image_tag(qiniu_image_path(cards.book.cover.url, :thumbnail => '100x100>')), book_path(cards.book_id)

            .info.col-sm-1.col-sm-offset-1.small
              %a{:href => event_user_words_path(cards.id)}#{truncate(cards.words, length:24)}
      %br

  %h3= "最新词卡..."
  %hr
  - recentcards.each do |cards|
    .row
      .subjectwrap

        #cover.col-sm-2
          - if cards.book != nil
            = link_to image_tag(qiniu_image_path(cards.book.cover.url, :thumbnail => '100x100>')), book_path(cards.book_id)

        .info.col-sm-5.col-sm-offset-1.small
          %p= "制卡人：#{cards.name}"
          %p= "适用年龄：#{cards.age}"
          %p= "制卡日期：#{cards.created_at.to_date}"
          %a{:href => event_user_words_path(cards.id)}#{cards.words}
    %br

%br

app/views/words/_displaycards2.html.haml
.index

  - mycards.each_slice(4) do |rows|
    .row
      - rows.each do |cards|
        .subjectwrap

          #cover.col-sm-1
            - if cards.book != nil
              = link_to image_tag(qiniu_image_path(cards.book.cover.url, :thumbnail => '75x75>')), book_path(cards.book_id)

          .info.col-sm-2.small
            %a{:href => event_user_words_path(cards.id)}#{truncate(cards.words, length:24)}
    %br

%br

app/views/words/_form.html.haml
%h1 卡片制作
%br

.record-form
  /= simple_form_for :event, :url => translate_path(:format => :pdf), :method => :post, html: { multipart: true, class: 'form-horizontal'}, wrapper: :horizontal_form do |f|
  = simple_form_for event, :url => translate_path, :method => :post, html: { multipart: true, class: 'form-horizontal'}, wrapper: :horizontal_form do |f|
    = f.input :name, as: :string, label: '姓名', input_html: {class:  'form-control'}
    = f.input :age, label: '年龄', input_html: {class:  'form-control'}
    = f.input :book_name, as: :string, label: '书名', input_html: {class:  'form-control'}
    = f.input :words, label: '输入单词', hint: '输入中英文皆可，支持两种方式：一是单词以逗号分隔，如hello,world,hurry up,good；二是单词加#例句#，如name #What is your name?#', as: :text, input_html: {class:  'form-control', rows: 10}, required: true
    
    = f.input :book_id, as: :integer, :as => :hidden, input_html: {class:  'form-control'}
    = f.input :user_id, as: :integer, :as => :hidden, input_html: {class:  'form-control'}
    = f.button :submit, "卡片生成", class: "btn btn-success btn-lg btn-block", :disable_with => "Submitting…"
    
  %br

单词释义由 
%a{:href => "http://fanyi.youdao.com/"}有道翻译 
提供。

//= link_to "卡片制作记录", events_path

%br

app/views/words/cards.html.haml
.row
  = render :partial => 'words/displaycards', layout: 'layouts/layout', :locals => { :mycards => @mycards, :recentcards => @recentcards }

app/views/words/index.html.haml
.row
  = render :partial => 'words/display', layout: 'layouts/layout', :locals => { :events => @events }

app/views/words/new.html.haml
.row
  = render :partial => 'words/form', layout: 'layouts/layout', :locals => { :event => @event }

app/views/words/translate.html.haml
%table.table-bordered
  - @target.each do |word, value|
    %tr.wordline
      %td.text-center= word.name if word != nil
      %td{:style => "width: 50%"}= simple_format word.to_cover(value).join("\n")
      /%td{:style => "width: 50%"}= simple_format value.join("\n")